version: "2"

services:
  nats:
    image: "nats:0.9.6"
    entrypoint: "/gnatsd -p 4222"
    ports:
      - "4222:4222"
  nats-proxy:
    build: .
    depends_on:
      - nats
    ports:
      - "4223:4223"
